export const FETCH_LOGIN_ADMIN_SUCCESS = '@@loginAdmin/FETCH_LOGIN_ADMIN_SUCCESS';
export const FETCH_LOGIN_ADMIN_REQUEST = '@@loginAdmin/FETCH_LOGIN_ADMIN_REQUEST';
export const FETCH_LOGIN_ADMIN_FAIL = '@@loginAdmin/FETCH_LOGIN_ADMIN_FAIL';
