export const FETCH_EDIT_VITRI_SUCCESS = '@@quanlyvitri/FETCH_EDIT_VITRI_SUCCESS';
export const FETCH_EDIT_VITRI_REQUEST = '@@quanlyvitri/FETCH_EDIT_VITRI_REQUEST';
export const FETCH_EDIT_VITRI_FAIL = '@@quanlyvitri/FETCH_EDIT_VITRI_FAIL';