export const FETCH_DELETE_BOOK_ROOM_SUCCESS = '@@quanlydatphong/FETCH_DELETE_BOOK_ROOM_SUCCESS';
export const FETCH_DELETE_BOOK_ROOM_REQUEST = '@@quanlydatphong/FETCH_DELETE_BOOK_ROOM_REQUEST';
export const FETCH_DELETE_BOOK_ROOM_FAIL = '@@quanlydatphong/FETCH_DELETE_BOOK_ROOM_FAIL';