export const FETCH_DANH_SACH_VITRI_SUCCESS = '@@quanlyvitri/FETCH_DANH_SACH_VITRI_SUCCESS';
export const FETCH_DANH_SACH_VITRI_REQUEST = '@@quanlyvitri/FETCH_DANH_SACH_VITRI_REQUEST';
export const FETCH_DANH_SACH_VITRI_FAIL = '@@quanlyvitri/FETCH_DANH_SACH_VITRI_FAIL';

export const SEARCH_VITRI_DASHBOARD = '@@quanlyvitri/SEARCH_VITRI_DASHBOARD';