export const FETCH_USER_LIST_PHONGDADAT_SUCCESS = '@@user/FETCH_USER_LIST_PHONGDADAT_SUCCESS';
export const FETCH_USER_LIST_PHONGDADAT_REQUEST = '@@user/FETCH_USER_LIST_PHONGDADAT_REQUEST';
export const FETCH_USER_LIST_PHONGDADAT_FAIL = '@@user/FETCH_USER_LIST_PHONGDADAT_FAIL';


export const FETCH_DELETE_PHONGDADAT_SUCCESS = '@@user/FETCH_DELETE_PHONGDADAT_SUCCESS';
export const FETCH_DELETE_PHONGDADAT_REQUEST = '@@user/FETCH_DELETE_PHONGDADAT_REQUEST';
export const FETCH_DELETE_PHONGDADAT_FAIL = '@@user/FETCH_DELETE_PHONGDADAT_FAIL';