export const FETCH_INFO_VITRI_SUCCESS = '@@quanlyvitri/FETCH_INFO_VITRI_SUCCESS';
export const FETCH_INFO_VITRI_REQUEST = '@@quanlyvitri/FETCH_INFO_VITRI_REQUEST';
export const FETCH_INFO_VITRI_FAIL = '@@quanlyvitri/FETCH_INFO_VITRI_FAIL';