export const FETCH_DANH_SACH_BOOK_ROOM_SUCCESS = '@@quanlydatphong/FETCH_DANH_SACH_BOOK_ROOM_SUCCESS';
export const FETCH_DANH_SACH_BOOK_ROOM_REQUEST = '@@quanlydatphong/FETCH_DANH_SACH_BOOK_ROOM_REQUEST';
export const FETCH_DANH_SACH_BOOK_ROOM_FAIL = '@@quanlydatphong/FETCH_DANH_SACH_BOOK_ROOM_FAIL';

export const SEARCH_BOOK_ROOM_DASHBOARD = '@@quanlydatphong/SEARCH_BOOK_ROOM_DASHBOARD';
