export const FETCH_REGISTER_SUCCESS = '@@registerPage/FETCH_REGISTER_SUCCESS';
export const FETCH_REGISTER_REQUEST = '@@registerPage/FETCH_REGISTER_REQUEST';
export const FETCH_REGISTER_FAIL = '@@registerPage/FETCH_REGISTER_FAIL';
