export const FETCH_PHONGTHUE_THEO_MAVITRI_SUCCESS = '@@searchpage/FETCH_PHONGTHUE_THEO_MAVITRI_SUCCESS';
export const FETCH_PHONGTHUE_THEO_MAVITRI_REQUEST = '@@searchpage/FETCH_PHONGTHUE_THEO_MAVITRI_REQUEST';
export const FETCH_PHONGTHUE_THEO_MAVITRI_FAIL = '@@searchpage/FETCH_PHONGTHUE_THEO_MAVITRI_FAIL';