export const FETCH_CHITIET_PHONGTHUE_SUCCESS = '@@detailpage/FETCH_CHITIET_PHONGTHUE_SUCCESS';
export const FETCH_CHITIET_PHONGTHUE_REQUEST = '@@detailpage/FETCH_CHITIET_PHONGTHUE_REQUEST';
export const FETCH_CHITIET_PHONGTHUE_FAIL = '@@detailpage/FETCH_CHITIET_PHONGTHUE_FAIL';

export const FETCH_CHITIET_VITRI_SUCCESS = '@@detailpage/FETCH_CHITIET_VITRI_SUCCESS';
export const FETCH_CHITIET_VITRI_REQUEST = '@@detailpage/FETCH_CHITIET_VITRI_REQUEST';
export const FETCH_CHITIET_VITRI_FAIL = '@@detailpage/FETCH_CHITIET_VITRI_FAIL';

