export const FETCH_DELETE_VITRI_SUCCESS = '@@quanlyvitri/FETCH_DELETE_VITRI_SUCCESS';
export const FETCH_DELETE_VITRI_REQUEST = '@@quanlyvitri/FETCH_DELETE_VITRI_REQUEST';
export const FETCH_DELETE_VITRI_FAIL = '@@quanlyvitri/FETCH_DELETE_VITRI_FAIL';