export const FETCH_UPLOAD_IMG_SUCCESS = '@@user/FETCH_UPLOAD_IMG_SUCCESS';
export const FETCH_UPLOAD_IMG_REQUEST = '@@user/FETCH_UPLOAD_IMG_REQUEST';
export const FETCH_UPLOAD_IMG_FAIL = '@@user/FETCH_UPLOAD_IMG_FAIL';
