export const FETCH_DELETE_ROOM_SUCCESS = '@@quanlyphong/FETCH_DELETE_ROOM_SUCCESS';
export const FETCH_DELETE_ROOM_REQUEST = '@@quanlyphong/FETCH_DELETE_ROOM_REQUEST';
export const FETCH_DELETE_ROOM_FAIL = '@@quanlyphong/FETCH_DELETE_ROOM_FAIL';