export const FETCH_BINHLUAN_THEOPHONG_SUCCESS = '@@detailpage/FETCH_BINHLUAN_THEOPHONG_SUCCESS';
export const FETCH_BINHLUAN_THEOPHONG_REQUEST = '@@detailpage/FETCH_BINHLUAN_THEOPHONG_REQUEST';
export const FETCH_BINHLUAN_THEOPHONG_FAIL = '@@detailpage/FETCH_BINHLUAN_THEOPHONG_FAIL';

export const FETCH_ADD_BINHLUAN_SUCCESS = '@@detailpage/FETCH_ADD_BINHLUAN_SUCCESS';
export const FETCH_ADD_BINHLUAN_REQUEST = '@@detailpage/FETCH_ADD_BINHLUAN_REQUEST';
export const FETCH_ADD_BINHLUAN_FAIL = '@@detailpage/FETCH_ADD_BINHLUAN_FAIL';


export const FETCH_BINHLUAN_SUCCESS = '@@detailpage/FETCH_BINHLUAN_SUCCESS';
export const FETCH_BINHLUAN_REQUEST = '@@detailpage/FETCH_BINHLUAN_REQUEST';
export const FETCH_BINHLUAN_FAIL = '@@detailpage/FETCH_BINHLUAN_FAIL';

export const MA_PHONG = '@@detailpage/MA_PHONG';