export const FETCH_EDIT_BOOK_ROOM_SUCCESS = '@@quanlydatphong/FETCH_EDIT_BOOK_ROOM_SUCCESS';
export const FETCH_EDIT_BOOK_ROOM_REQUEST = '@@quanlydatphong/FETCH_EDIT_BOOK_ROOM_REQUEST';
export const FETCH_EDIT_BOOK_ROOM_FAIL = '@@quanlydatphong/FETCH_EDIT_BOOK_ROOM_FAIL';